Add `macos.archive_files`
pfirsich/makelove pull request #35
Opened 2023-05-18 16:36 UTC by Maiori44

This PR adds `macos.archive_files`, which works the same way as `windows.archive_files`, but for MacOS instead.
Files are stored in `<name>/Contents/Resources/`.
This PR has been tested with single files and directories (that included files and more directories inside).
Additionally, `archive_files` is now used for MacOS too, not only Windows.

2023-05-18 16:37 UTC, Maiori44 commented
If this is merged issue #33 can probably also be closed.

2023-05-22 09:56 UTC, pfirsich commented
When you test it again, could you please also try using the top-level `[archive_files]`. Of course it should make not difference, but it would be good to see, if you test it again anyways.

2023-05-22 09:58 UTC, Maiori44 commented
I already did in my original testing

2023-05-22 14:39 UTC, pfirsich requested changes

2023-05-22 14:42 UTC, Maiori44 commented on makelove/macos.py
> +                for file_path in directory.glob("**/*"):
no idea how to test this tbh

2023-05-22 14:43 UTC, Maiori44 commented on makelove_full.toml
> +# This specifies the files to be included in the zip archives generated for windows and macos builds.
maybe the more detailed explenation should be put in macos.archive_files' explenation, not this one

2023-05-22 14:43 UTC, Maiori44 commented on makelove/macos.py
> +        for k, v in archive_files.items():
good idea

2023-05-22 17:27 UTC, pfirsich commented on makelove/macos.py
> +                for file_path in directory.glob("**/*"):
Put a directory into archive_files and then put a hidden file in there (a file with a name that starts with a period `.`).

2023-05-22 17:28 UTC, pfirsich commented on makelove_full.toml
> +# This specifies the files to be included in the zip archives generated for windows and macos builds.
That's a great point. This top level `[archive_files]` should probably just say that this is a way to specify files for all targets and one should look at the descriptions of the platform specific `archive_files` to see what it does.

2023-05-24 06:22 UTC, Maiori44 commented on makelove/macos.py
> +                for file_path in directory.glob("**/*"):
I tested this and it did include the hidden file.

2023-05-25 20:19 UTC, merged